"""ms-95 / e-2406 — lazy fetch entries on toggle-ms expand.

Initial project load (selectProject) only pre-fetches entries for in_progress
milestones. Without lazy fetch in handleCommonAction('toggle-ms'), expanding
any done / observing / waiting / todo milestone renders an empty body.

This pins both the Web (server/static) and Desktop (desktop/dist) bundles so
the regression can't slip back in via a partial revert or future refactor.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB_INDEX = ROOT / "server" / "static" / "index.html"
DESKTOP_INDEX = ROOT / "desktop" / "dist" / "index.html"


def _read(p: Path) -> str:
    return p.read_text(encoding="utf-8")


def _extract_toggle_ms_block(src: str) -> str:
    """Return the body of the case 'toggle-ms' branch in handleCommonAction."""
    marker = "case 'toggle-ms': {"
    start = src.index(marker)
    # naive scan to the matching closing brace for the case block
    depth = 0
    i = start + len(marker)
    while i < len(src):
        ch = src[i]
        if ch == "{":
            depth += 1
        elif ch == "}":
            if depth == 0:
                return src[start : i + 1]
            depth -= 1
        i += 1
    raise AssertionError("toggle-ms case block not found / unbalanced braces")


class TestWebUI:
    def setup_method(self, _method):
        self.block = _extract_toggle_ms_block(_read(WEB_INDEX))

    def test_lazy_fetches_entries_on_first_expand(self):
        assert "fetchMilestoneEntries(msId)" in self.block, (
            "toggle-ms must lazy-fetch entries on first expand, otherwise "
            "non-active MS cards render empty (e-2406)."
        )

    def test_lazy_fetch_guarded_by_cache_miss(self):
        assert "state.milestoneEntries[msId] === undefined" in self.block, (
            "fetchMilestoneEntries must be guarded by a cache-miss check "
            "to avoid refetching on every toggle."
        )

    def test_lazy_fetch_only_on_expand_not_collapse(self):
        assert "if (!wasExpanded)" in self.block, (
            "Lazy fetch must be gated on the expand direction, not fire "
            "when the user collapses the card."
        )


class TestDesktopBundle:
    """Mirror the same pins on the Tauri bundle (regenerated by desktop/build.py)."""

    def setup_method(self, _method):
        self.block = _extract_toggle_ms_block(_read(DESKTOP_INDEX))

    def test_lazy_fetches_entries_on_first_expand(self):
        assert "fetchMilestoneEntries(msId)" in self.block

    def test_lazy_fetch_guarded_by_cache_miss(self):
        assert "state.milestoneEntries[msId] === undefined" in self.block

    def test_lazy_fetch_only_on_expand_not_collapse(self):
        assert "if (!wasExpanded)" in self.block
