"""Trek tab presence + render-function pin (ms-69 / e-1659).

Checks that:
  - The Treks tab button exists in the tab-bar
  - The render branch for state.activeTab === 'treks' is wired up
  - renderTreksSection / openTrek / closeTrek / loadTreks / loadTrekDocs all
    appear in the source (the Web UI bundles JS inline in index.html, so
    presence in source = presence at runtime)
  - desktop/dist/index.html (the Tauri-rendered copy) inherits all of the
    above except the data fetching layer (Tauri uses desktop/layer.js for
    network I/O; this test allows that gap)

These checks are deliberately textual rather than DOM-rendering so we don't
need a headless browser in CI. The Tauri build (`desktop/build.py`) is
exercised separately by the drift detector in pre-commit.
"""

from __future__ import annotations

import pathlib

import pytest


REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
WEB_INDEX = REPO_ROOT / "server" / "static" / "index.html"
DESKTOP_INDEX = REPO_ROOT / "desktop" / "dist" / "index.html"


def _read(path: pathlib.Path) -> str:
    return path.read_text(encoding="utf-8")


class TestWebUI_TrekTab:
    """server/static/index.html — the canonical Web UI bundle."""

    def setup_method(self, _method):
        self.src = _read(WEB_INDEX)

    def test_tab_button_exists(self):
        assert 'data-tab="treks"' in self.src, (
            'Treks tab button missing from tab-bar'
        )
        # Label visible on the button
        assert ">Treks<" in self.src

    def test_render_branch_wired(self):
        # `state.activeTab === 'treks'` triggers renderTreksSection()
        assert "state.activeTab === 'treks'" in self.src
        assert "renderTreksSection()" in self.src

    def test_state_fields_initialised(self):
        # Treks list + open-trek + open-trek-docs all initialised so the
        # render function doesn't blow up before the first fetch.
        for field in ("treks: [],", "openTrekId: null,", "openTrekDocs: []"):
            assert field in self.src, f"state field {field!r} missing"

    def test_data_source_methods(self):
        for fn in ("loadTreks: async", "loadTrekDocs: async"):
            assert fn in self.src, f"dataSource.{fn} missing"

    def test_open_and_close_handlers(self):
        for fn in (
            "function openTrek(",
            "function closeTrek(",
            "function renderTreksSection(",
            "function _renderTrekDetail(",
        ):
            assert fn in self.src, f"function {fn!r} missing"

    def test_action_handler_cases(self):
        for case in ("case 'open-trek':", "case 'close-trek':"):
            assert case in self.src, f"action handler {case!r} missing"

    def test_switch_tab_handles_treks(self):
        # switchTab('treks') should fetch the trek list
        # (= state.treks is reloaded on tab open)
        assert "if (tab === 'treks')" in self.src
        assert "dataSource.loadTreks()" in self.src


class TestDesktopUI_TrekTab:
    """desktop/dist/index.html — Tauri build of the same UI.

    The dist file is regenerated by desktop/build.py from server/static.
    The build strips SKIP blocks (Web-only fetch / api() helpers etc.) so
    we don't assert dataSource methods here. The visible UI surface and
    handler dispatch should mirror the Web copy.
    """

    def setup_method(self, _method):
        self.src = _read(DESKTOP_INDEX)

    def test_tab_button_exists(self):
        assert 'data-tab="treks"' in self.src

    def test_render_branch_wired(self):
        assert "state.activeTab === 'treks'" in self.src
        assert "renderTreksSection()" in self.src

    def test_render_functions_present(self):
        for fn in (
            "function openTrek(",
            "function closeTrek(",
            "function renderTreksSection(",
        ):
            assert fn in self.src, f"function {fn!r} missing from desktop bundle"
