"""ms-119 / e-4005 — 目的達成 evidence is generated by an independent judge, not
the implementer.

This session over-claimed ms-119 done because the *evidence* for the attainment
verdict was written by the implementer session. The fix separates the two:

  - the verdict stays the human's (SPEC § 方針2, enforced by the e-4006 approve
    guard), but
  - the *evidence* is produced by a context-zero judge handed only the SPEC 原典
    + criteria + optional diff — never implementer narrative.

``assemble_attainment_context`` is the structural bundle that carries exactly
that and nothing more. These tests pin its shape + the independence invariant.
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "lib"))
import review_spine  # noqa: E402


def test_bundle_carries_spec_criteria_and_no_implementer_narrative():
    b = review_spine.assemble_attainment_context(
        target_id="ms-119",
        spec_origin_id="specDoc1",
        spec_content="## やる\n発火スパイン ...",
        criteria=[{"source": "acceptance_criteria", "text": "AC1 ..."}],
        target_ref="ms-119",
        diff_text="+code",
    )
    assert b["review_type"] == review_spine.REVIEW_ATTAINMENT
    assert b["target_id"] == "ms-119"
    assert b["origin"]["content"].startswith("## やる")
    assert b["criteria"][0]["source"] == "acceptance_criteria"
    assert b["artifact"]["content"] == "+code"
    # verdict stays human — the bundle says so structurally
    assert b["verdict_ownership"] == "human"
    # no implementer-narrative keys leak into the judge's input
    forbidden = {"session", "intent", "narrative", "conversation", "author_notes",
                 "self_report"}
    assert forbidden.isdisjoint(b.keys())


def test_judge_contract_forbids_self_report_and_owns_only_evidence():
    b = review_spine.assemble_attainment_context(
        target_id="ms-1", spec_origin_id="d", spec_content="x",
        criteria=[], target_ref="ms-1",
    )
    jc = b["judge_contract"]
    # verifies against real code, not the implementer's self-report
    assert "自己申告" in jc
    assert "実コード" in jc
    # produces evidence, not the verdict — the human confirms
    assert "verdict" in jc and "human" in jc
    # context-zero: must not read the implementer session narrative
    assert "文脈ゼロ" in jc
    # the shared independence contract is also present
    assert "計器" in b["independence_contract"]


def test_missing_spec_is_a_gap_not_a_crash():
    b = review_spine.assemble_attainment_context(
        target_id="ms-9", spec_origin_id="", spec_content="",
        criteria=[], target_ref="ms-9",
        gaps=["ms-9 に SPEC 原典が紐づいていません"],
    )
    assert b["origin"]["id"] == ""
    assert b["gaps"] == ["ms-9 に SPEC 原典が紐づいていません"]


def test_diff_is_optional():
    b = review_spine.assemble_attainment_context(
        target_id="op-1", spec_origin_id="d", spec_content="s",
        criteria=[], target_ref="op-1",
    )
    assert b["artifact"]["content"] == ""


# --- CLI wiring: --type attainment requires --target, resolves SPEC ---
import subprocess

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COMMANDS = os.path.join(REPO, "lib", "commands.py")


def _run(env_extra):
    env = dict(os.environ)
    env.update(env_extra)
    return subprocess.run([sys.executable, COMMANDS, "review_context"],
                          capture_output=True, text=True, env=env, cwd=REPO)


def test_cli_attainment_requires_target():
    p = _run({"BEACON_REVIEW_TYPE": "attainment"})
    assert p.returncode == 1
    assert "--target" in p.stderr
    assert "Traceback" not in p.stderr  # clean error, not a stack trace
