"""Trek tab presence + render-function pin (ms-69 / e-1659).

Checks that:
  - The Treks tab button exists in the tab-bar
  - The render branch for state.activeTab === 'treks' is wired up
  - renderTreksSection / openTrek / closeTrek / loadTreks / loadTrekDocs all
    appear in the source (the Web UI bundles JS inline in index.html, so
    presence in source = presence at runtime)
  - desktop/dist/index.html (the Tauri-rendered copy) inherits all of the
    above except the data fetching layer (Tauri uses desktop/layer.js for
    network I/O; this test allows that gap)

These checks are deliberately textual rather than DOM-rendering so we don't
need a headless browser in CI. The Tauri build (`desktop/build.py`) is
exercised separately by the drift detector in pre-commit.
"""

from __future__ import annotations

import pathlib

import pytest


REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
WEB_INDEX = REPO_ROOT / "server" / "static" / "index.html"
DESKTOP_INDEX = REPO_ROOT / "desktop" / "dist" / "index.html"


def _read(path: pathlib.Path) -> str:
    return path.read_text(encoding="utf-8")


class TestWebUI_TrekTab:
    """server/static/index.html — the canonical Web UI bundle."""

    def setup_method(self, _method):
        self.src = _read(WEB_INDEX)

    def test_tab_button_exists(self):
        assert 'data-tab="treks"' in self.src, (
            'Treks tab button missing from tab-bar'
        )
        # Label visible on the button
        assert ">Treks<" in self.src

    def test_render_branch_wired(self):
        # `state.activeTab === 'treks'` triggers renderTreksSection()
        assert "state.activeTab === 'treks'" in self.src
        assert "renderTreksSection()" in self.src

    def test_state_fields_initialised(self):
        # Treks list + open-trek + open-trek-docs all initialised so the
        # render function doesn't blow up before the first fetch.
        for field in ("treks: [],", "openTrekId: null,", "openTrekDocs: []"):
            assert field in self.src, f"state field {field!r} missing"

    def test_data_source_methods(self):
        for fn in ("loadTreks: async", "loadTrekDocs: async"):
            assert fn in self.src, f"dataSource.{fn} missing"

    def test_open_and_close_handlers(self):
        for fn in (
            "function openTrek(",
            "function closeTrek(",
            "function renderTreksSection(",
            "function _renderTrekDetail(",
        ):
            assert fn in self.src, f"function {fn!r} missing"

    def test_action_handler_cases(self):
        for case in ("case 'open-trek':", "case 'close-trek':"):
            assert case in self.src, f"action handler {case!r} missing"

    def test_switch_tab_handles_treks(self):
        # switchTab('treks') should fetch the trek list
        # (= state.treks is reloaded on tab open)
        assert "if (tab === 'treks')" in self.src
        assert "dataSource.loadTreks()" in self.src


class TestDesktopUI_TrekTab:
    """desktop/dist/index.html — Tauri build of the same UI.

    The dist file is regenerated by desktop/build.py from server/static.
    The build strips SKIP blocks (Web-only fetch / api() helpers etc.) so
    we don't assert dataSource methods here. The visible UI surface and
    handler dispatch should mirror the Web copy.
    """

    def setup_method(self, _method):
        self.src = _read(DESKTOP_INDEX)

    def test_tab_button_exists(self):
        assert 'data-tab="treks"' in self.src

    def test_render_branch_wired(self):
        assert "state.activeTab === 'treks'" in self.src
        assert "renderTreksSection()" in self.src

    def test_render_functions_present(self):
        for fn in (
            "function openTrek(",
            "function closeTrek(",
            "function renderTreksSection(",
        ):
            assert fn in self.src, f"function {fn!r} missing from desktop bundle"


# ---------------------------------------------------------------------------
# Mock parity (ms-69 / e-1659 v2 — wireframe refactor)
#
# After the v2 refactor, the trek detail view mirrors mocks/trek-ui-v1.html
# point-for-point: full-page layout with crumb / head / meta grid / STOP card
# / Archive card / SCOPE / MEMBERS & SESSIONS / ACTIVE CLAIMS (placeholder) /
# RECENT ACTIVITY (placeholder) / SUMMARIES sections. These tests pin the
# structural elements so a future "simplify" edit can't silently lose the
# mock fidelity.
# ---------------------------------------------------------------------------

class TestWebUI_TrekMockParity:
    def setup_method(self, _method):
        self.src = _read(WEB_INDEX)

    def test_trek_palette_css_present(self):
        for cls in (
            ".trek-crumb",
            ".trek-head",
            ".trek-title-row",
            ".trek-badge",
            ".trek-stats",
            ".trek-meta",
            ".trek-stop-card",
            ".trek-archive-card",
            ".trek-section",
            ".trek-section-title",
            ".trek-scope-row",
            ".trek-member-row",
            ".trek-claim-row",
            ".trek-activity-row",
            ".trek-summary-row",
            ".trek-cli-hint",
            ".trek-coming-soon",
            ".trek-list-row",
        ):
            assert cls in self.src, f"CSS class {cls!r} missing from trek palette"

    def test_detail_view_renders_mock_sections(self):
        for header in (
            "SCOPE",
            "MEMBERS &amp; SESSIONS",
            "ACTIVE CLAIMS",
            "RECENT ACTIVITY",
            "SUMMARIES",
        ):
            assert header in self.src, f"section {header!r} missing from trek detail"

    def test_detail_view_uses_full_page_crumb_back_link(self):
        # The mock uses "← Back to TREKS" instead of an inline retro-back tab.
        assert "Back to TREKS" in self.src
        assert 'class="trek-crumb"' in self.src

    def test_stop_card_invokes_cli(self):
        # STOP / Resume buttons surface the CLI command (= editing is
        # terminal-only per ux-principle-no-terminal).
        assert "STOP THIS TREK" in self.src
        assert "trek-cli-hint" in self.src
        assert "case 'trek-cli-hint':" in self.src

    def test_unimplemented_sections_have_explanatory_placeholders(self):
        # ACTIVE CLAIMS / RECENT ACTIVITY are placeholders pointing at the
        # follow-up MS / tasks until backing data lands.
        assert "ms-55" in self.src  # ACTIVE CLAIMS placeholder
        assert "e-1696" in self.src  # RECENT ACTIVITY placeholder
        assert ("e-1697" in self.src) or ("beacon morning" in self.src)
        assert ("e-1698" in self.src) or ("beacon trek summary" in self.src)

    def test_list_row_uses_mock_class(self):
        # The list row has a distinct class (not retro-item) so the mock-style
        # status dot / id chip render correctly.
        assert 'class="trek-list-row"' in self.src


class TestDesktopUI_TrekMockParity:
    def setup_method(self, _method):
        self.src = _read(DESKTOP_INDEX)

    def test_palette_css_carried_into_tauri_bundle(self):
        for cls in (".trek-crumb", ".trek-head", ".trek-stop-card",
                    ".trek-scope-row", ".trek-member-row", ".trek-list-row"):
            assert cls in self.src, f"CSS class {cls!r} missing from desktop bundle"

    def test_sections_present_in_tauri_bundle(self):
        for header in ("SCOPE", "MEMBERS &amp; SESSIONS", "ACTIVE CLAIMS",
                       "RECENT ACTIVITY", "SUMMARIES"):
            assert header in self.src, f"section {header!r} missing"
