"""Beacon Claim primitives (ms-55 e-1648).

The "走る側" core of ms-55 SPEC: how parallel agents share which piece
of work each one has taken, so two agents don't double-spend on the
same task and a session restart can recover "what was I in the middle
of?".

Three primitive kinds (SPEC §5):

  * **request**: "Will you take X?" Receiver must accept or decline
    (= 受諾必須). Used when one agent has identified work but needs
    another to do it (different cwd, different OS, different skill set).

  * **handoff**: "I was on X, you take it now." Receiver must accept or
    decline. Used when an agent is leaving / context-running-out and
    needs to transfer in-progress state.

  * **claim**: "I'm taking X." First-publisher-wins broadcast (= no
    receiver consent needed). Used as the default coordination mode —
    every agent broadcasts what they pick up; conflicts surface at
    `latest_claims_by_target` time.

Wire format (= what lands on the bus, channel = `claim-signal`):

  {
    "kind": "claim",                 # discriminator
    "claim_kind": "request" | "handoff" | "claim",
    "claim_id": "cl-1750000000-abc",  # generated by build_claim_payload
    "target": {                      # what's being claimed
      "kind": "ms" | "task" | "operation" | "trek" | "free",
      "id":   "ms-55" / "e-1646" / ...
    },
    "from_session_id": "sv-...",     # who is claiming / handing off / requesting
    "to_session_id":   "sv-..."      # required for request / handoff;
                                     # empty for claim (broadcast)
    "intent": "free text — what specifically about target",
    "expires_at": "2026-06-16T00:00:00Z",  # optional auto-expiry
    "issued_at":  "2026-06-15T00:00:00Z",
    "metadata":   { ... }            # optional structured detail
  }

  # Response (for request / handoff):
  {
    "kind": "claim_response",
    "claim_id": "cl-1750000000-abc",
    "decision": "accept" | "decline",
    "from_session_id": "sv-...",      # the responder
    "reason": "free text",
    "issued_at": "..."
  }

  # Release (= "I'm done with this claim, others can take it"):
  {
    "kind": "claim_release",
    "claim_id": "cl-1750000000-abc",
    "from_session_id": "sv-...",
    "outcome": "completed" | "abandoned",
    "reason": "free text",
    "issued_at": "..."
  }

Persistence:

  Local mode: .beacon/active_claims.json — a single JSON dict
  keyed by claim_id, mirroring what the server-side subcollection
  would look like. Atomic write via temp-file + rename.

  Cloud mode: an `active_claims/` subcollection on the project
  document is the intended layout (matches v2 schema patterns).
  This module currently writes local-only; the cloud path lives in
  a TODO at the bottom of the file.

The CLI in lib/commands.py wraps these helpers into:

  beacon claim request --target ms:ms-55 --to sv-... --intent "..."
  beacon claim handoff --target task:e-1646 --to sv-... --intent "..."
  beacon claim post    --target task:e-1646 --intent "..."
  beacon claim list   [--mine] [--target ms:ms-55] [--json]
  beacon claim release <claim_id> [--outcome completed|abandoned]
"""

from __future__ import annotations

import json
import os
import secrets
import tempfile
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional


# ---------------------------------------------------------------------------
# Channel + payload constants
# ---------------------------------------------------------------------------

CLAIM_CHANNEL = "claim-signal"

PAYLOAD_KIND_CLAIM = "claim"
PAYLOAD_KIND_CLAIM_RESPONSE = "claim_response"
PAYLOAD_KIND_CLAIM_RELEASE = "claim_release"

CLAIM_KIND_REQUEST = "request"
CLAIM_KIND_HANDOFF = "handoff"
CLAIM_KIND_CLAIM = "claim"
_VALID_CLAIM_KINDS = frozenset({
    CLAIM_KIND_REQUEST, CLAIM_KIND_HANDOFF, CLAIM_KIND_CLAIM,
})

#: Target kinds for claims. Wider than stop's target kinds because a
#: claim can lock onto an Operation or a free-form scope ("I'm doing
#: the AWS investigation") that doesn't have a beacon entry yet.
TARGET_MS = "ms"
TARGET_TASK = "task"
TARGET_OPERATION = "operation"
TARGET_TREK = "trek"
TARGET_FREE = "free"
_VALID_TARGET_KINDS = frozenset({
    TARGET_MS, TARGET_TASK, TARGET_OPERATION, TARGET_TREK, TARGET_FREE,
})

RESPONSE_ACCEPT = "accept"
RESPONSE_DECLINE = "decline"
_VALID_RESPONSES = frozenset({RESPONSE_ACCEPT, RESPONSE_DECLINE})

OUTCOME_COMPLETED = "completed"
OUTCOME_ABANDONED = "abandoned"
_VALID_OUTCOMES = frozenset({OUTCOME_COMPLETED, OUTCOME_ABANDONED})


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _utcnow_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def mint_claim_id() -> str:
    """Stable, sortable, collision-resistant claim id.

    Format: cl-<unix ts>-<6 hex chars>. Sorting by id naturally orders
    by issue time which makes "who got there first" comparisons trivial.
    """
    return f"cl-{int(time.time())}-{secrets.token_hex(3)}"


# ---------------------------------------------------------------------------
# Builders
# ---------------------------------------------------------------------------

def build_claim_payload(
    *,
    claim_kind: str,
    from_session_id: str,
    target_kind: str,
    target_id: str,
    intent: str = "",
    to_session_id: str = "",
    expires_at: str = "",
    claim_id: Optional[str] = None,
    metadata: Optional[dict] = None,
    issued_at: Optional[str] = None,
) -> dict:
    """Build a validated claim payload.

    Request / handoff REQUIRE to_session_id (= specific recipient).
    Plain claim (= broadcast) MUST NOT set to_session_id.

    Returns a fresh dict with a `claim_id` minted if the caller didn't
    pass one. Mint-on-build means the sender can reference the id
    immediately (= print it to the user, persist locally before the
    bus call returns).
    """
    if claim_kind not in _VALID_CLAIM_KINDS:
        raise ValueError(
            f"claim_kind must be one of {sorted(_VALID_CLAIM_KINDS)}, "
            f"got {claim_kind!r}"
        )
    if not from_session_id:
        raise ValueError("from_session_id is required")
    if target_kind not in _VALID_TARGET_KINDS:
        raise ValueError(
            f"target_kind must be one of {sorted(_VALID_TARGET_KINDS)}, "
            f"got {target_kind!r}"
        )
    if not target_id:
        raise ValueError("target_id is required")
    if claim_kind in (CLAIM_KIND_REQUEST, CLAIM_KIND_HANDOFF):
        if not to_session_id:
            raise ValueError(
                f"claim_kind={claim_kind} requires to_session_id "
                "(use claim_kind=claim for broadcast)"
            )
    else:  # CLAIM_KIND_CLAIM
        if to_session_id:
            raise ValueError(
                "claim_kind=claim must not set to_session_id "
                "(use request/handoff for targeted claims)"
            )

    payload: dict = {
        "kind": PAYLOAD_KIND_CLAIM,
        "claim_kind": claim_kind,
        "claim_id": claim_id or mint_claim_id(),
        "target": {"kind": target_kind, "id": target_id},
        "from_session_id": from_session_id,
        "intent": intent or "",
        "issued_at": issued_at or _utcnow_iso(),
    }
    if to_session_id:
        payload["to_session_id"] = to_session_id
    if expires_at:
        payload["expires_at"] = expires_at
    if metadata is not None:
        if not isinstance(metadata, dict):
            raise ValueError("metadata must be a dict if provided")
        payload["metadata"] = metadata
    return payload


def build_response_payload(
    *,
    claim_id: str,
    decision: str,
    from_session_id: str,
    reason: str = "",
    issued_at: Optional[str] = None,
) -> dict:
    if not claim_id:
        raise ValueError("claim_id is required")
    if decision not in _VALID_RESPONSES:
        raise ValueError(
            f"decision must be one of {sorted(_VALID_RESPONSES)}, "
            f"got {decision!r}"
        )
    if not from_session_id:
        raise ValueError("from_session_id is required")
    return {
        "kind": PAYLOAD_KIND_CLAIM_RESPONSE,
        "claim_id": claim_id,
        "decision": decision,
        "from_session_id": from_session_id,
        "reason": reason or "",
        "issued_at": issued_at or _utcnow_iso(),
    }


def build_release_payload(
    *,
    claim_id: str,
    outcome: str,
    from_session_id: str,
    reason: str = "",
    issued_at: Optional[str] = None,
) -> dict:
    if not claim_id:
        raise ValueError("claim_id is required")
    if outcome not in _VALID_OUTCOMES:
        raise ValueError(
            f"outcome must be one of {sorted(_VALID_OUTCOMES)}, "
            f"got {outcome!r}"
        )
    if not from_session_id:
        raise ValueError("from_session_id is required")
    return {
        "kind": PAYLOAD_KIND_CLAIM_RELEASE,
        "claim_id": claim_id,
        "outcome": outcome,
        "from_session_id": from_session_id,
        "reason": reason or "",
        "issued_at": issued_at or _utcnow_iso(),
    }


# ---------------------------------------------------------------------------
# Parsers
# ---------------------------------------------------------------------------

def parse_claim_event(event: dict) -> Optional[dict]:
    """Pull a normalized claim record out of a raw bus event.

    Returns None for malformed input (wrong channel, missing fields,
    unknown discriminator, etc.) — same forgiveness rule as
    stop_signal.parse_stop_event.
    """
    if not isinstance(event, dict):
        return None
    if event.get("channel") != CLAIM_CHANNEL:
        return None
    payload = event.get("payload") or {}
    if not isinstance(payload, dict):
        return None
    if payload.get("kind") != PAYLOAD_KIND_CLAIM:
        return None

    claim_kind = payload.get("claim_kind")
    if claim_kind not in _VALID_CLAIM_KINDS:
        return None
    target = payload.get("target") or {}
    if not isinstance(target, dict):
        return None
    tk = target.get("kind")
    ti = target.get("id")
    if tk not in _VALID_TARGET_KINDS or not ti:
        return None
    from_sid = payload.get("from_session_id") or ""
    if not from_sid:
        return None
    claim_id = payload.get("claim_id") or ""
    if not claim_id:
        return None
    record: dict = {
        "claim_id": claim_id,
        "claim_kind": claim_kind,
        "target": {"kind": tk, "id": ti},
        "from_session_id": from_sid,
        "intent": payload.get("intent") or "",
        "issued_at": payload.get("issued_at") or "",
        "event_id": event.get("event_id") or "",
    }
    to_sid = payload.get("to_session_id") or ""
    if to_sid:
        record["to_session_id"] = to_sid
    if payload.get("expires_at"):
        record["expires_at"] = payload["expires_at"]
    if isinstance(payload.get("metadata"), dict):
        record["metadata"] = payload["metadata"]
    return record


def parse_response_event(event: dict) -> Optional[dict]:
    if not isinstance(event, dict):
        return None
    if event.get("channel") != CLAIM_CHANNEL:
        return None
    payload = event.get("payload") or {}
    if not isinstance(payload, dict):
        return None
    if payload.get("kind") != PAYLOAD_KIND_CLAIM_RESPONSE:
        return None
    decision = payload.get("decision")
    if decision not in _VALID_RESPONSES:
        return None
    claim_id = payload.get("claim_id") or ""
    if not claim_id:
        return None
    from_sid = payload.get("from_session_id") or ""
    if not from_sid:
        return None
    return {
        "claim_id": claim_id,
        "decision": decision,
        "from_session_id": from_sid,
        "reason": payload.get("reason") or "",
        "issued_at": payload.get("issued_at") or "",
        "event_id": event.get("event_id") or "",
    }


def parse_release_event(event: dict) -> Optional[dict]:
    if not isinstance(event, dict):
        return None
    if event.get("channel") != CLAIM_CHANNEL:
        return None
    payload = event.get("payload") or {}
    if not isinstance(payload, dict):
        return None
    if payload.get("kind") != PAYLOAD_KIND_CLAIM_RELEASE:
        return None
    outcome = payload.get("outcome")
    if outcome not in _VALID_OUTCOMES:
        return None
    claim_id = payload.get("claim_id") or ""
    from_sid = payload.get("from_session_id") or ""
    if not claim_id or not from_sid:
        return None
    return {
        "claim_id": claim_id,
        "outcome": outcome,
        "from_session_id": from_sid,
        "reason": payload.get("reason") or "",
        "issued_at": payload.get("issued_at") or "",
        "event_id": event.get("event_id") or "",
    }


# ---------------------------------------------------------------------------
# Conflict detection (= "who got there first")
# ---------------------------------------------------------------------------

def latest_claims_by_target(events: list[dict]) -> dict[tuple, dict]:
    """Reduce an event stream to the currently-active claim per target.

    Walks the events oldest → newest and:
      * sets the claim for (target_kind, target_id) when seeing a claim
      * drops the entry when seeing a release for that claim_id
      * leaves request/handoff entries until they've been accepted —
        a request is a *proposal*, not a binding claim until accepted

    Response events flip pending request/handoff records to bound:
      * accept → the claim is honored; the to_session_id is now the owner
      * decline → the request is removed without binding anyone

    Returns a dict keyed by (target_kind, target_id). Each value is the
    active claim record. First-publisher-wins for plain `claim` kind:
    if two `claim` events land on the same target, the older one wins
    and the newer one is recorded in `_conflicts` for surface.
    """
    state: dict[tuple, dict] = {}

    sorted_events = sorted(
        (e for e in events if isinstance(e, dict)),
        key=lambda e: e.get("created_at") or "",
    )

    # Track pending request/handoff by claim_id so responses can bind them.
    pending: dict[str, dict] = {}

    for ev in sorted_events:
        if ev.get("channel") != CLAIM_CHANNEL:
            continue

        claim = parse_claim_event(ev)
        if claim:
            target_key = (claim["target"]["kind"], claim["target"]["id"])
            kind = claim["claim_kind"]

            if kind == CLAIM_KIND_CLAIM:
                if target_key in state:
                    # First-publisher-wins — record the conflict but
                    # don't displace the original owner.
                    existing = state[target_key]
                    existing.setdefault("_conflicts", []).append({
                        "claim_id": claim["claim_id"],
                        "from_session_id": claim["from_session_id"],
                        "issued_at": claim["issued_at"],
                    })
                else:
                    state[target_key] = dict(claim)
            else:  # request / handoff
                pending[claim["claim_id"]] = dict(claim)
                # Don't put it in state yet — it's a proposal until the
                # recipient accepts.

            continue

        response = parse_response_event(ev)
        if response:
            cid = response["claim_id"]
            if cid in pending:
                req = pending.pop(cid)
                if response["decision"] == RESPONSE_ACCEPT:
                    target_key = (req["target"]["kind"], req["target"]["id"])
                    # Acceptance binds the to_session_id as the owner of
                    # the work — but the claim record's "owner" is now
                    # the responder, not the issuer.
                    bound = dict(req)
                    bound["from_session_id"] = response["from_session_id"]
                    # Keep the issuer reachable for audit:
                    bound["issued_by_session_id"] = req["from_session_id"]
                    bound["accepted_at"] = response["issued_at"]
                    if target_key in state:
                        existing = state[target_key]
                        existing.setdefault("_conflicts", []).append({
                            "claim_id": bound["claim_id"],
                            "from_session_id": bound["from_session_id"],
                            "issued_at": bound["accepted_at"],
                        })
                    else:
                        state[target_key] = bound
                # decline → just drop pending; no state change
            continue

        release = parse_release_event(ev)
        if release:
            cid = release["claim_id"]
            # Find the target whose active claim has this claim_id and
            # remove it.
            for key, rec in list(state.items()):
                if rec.get("claim_id") == cid:
                    del state[key]
                    break
            # Also drop from pending if it never got accepted.
            pending.pop(cid, None)
            continue

    return state


# ---------------------------------------------------------------------------
# Local persistence (.beacon/active_claims.json)
# ---------------------------------------------------------------------------

def _active_claims_path(beacon_dir: Optional[str] = None) -> str:
    base = beacon_dir or os.environ.get("BEACON_DIR", "") or ".beacon"
    return os.path.join(base, "active_claims.json")


def _read_active_claims(beacon_dir: Optional[str] = None) -> dict:
    path = _active_claims_path(beacon_dir)
    if not os.path.exists(path):
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        if not isinstance(data, dict):
            return {}
        return data
    except (OSError, json.JSONDecodeError):
        return {}


def _write_active_claims(data: dict, *, beacon_dir: Optional[str] = None):
    """Atomic write via tempfile + rename, mirrored from session_log style."""
    base = beacon_dir or os.environ.get("BEACON_DIR", "") or ".beacon"
    os.makedirs(base, exist_ok=True)
    path = _active_claims_path(beacon_dir)
    fd, tmp = tempfile.mkstemp(prefix=".active_claims.", dir=base)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2, sort_keys=True)
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def record_local_claim(
    claim_payload: dict, *, beacon_dir: Optional[str] = None,
) -> None:
    """Persist a claim payload to the local active_claims store.

    Mirrors what the server-side subcollection would hold. Idempotent:
    re-writing the same claim_id overwrites the existing entry, which
    matches "the latest issue is the canonical record" semantics.
    """
    if not isinstance(claim_payload, dict):
        raise TypeError("claim_payload must be a dict")
    cid = claim_payload.get("claim_id")
    if not cid:
        raise ValueError("claim_payload must include claim_id")
    data = _read_active_claims(beacon_dir)
    data[cid] = claim_payload
    _write_active_claims(data, beacon_dir=beacon_dir)


def release_local_claim(
    claim_id: str, *, beacon_dir: Optional[str] = None,
) -> bool:
    """Drop a claim from the local store. Returns True if dropped."""
    data = _read_active_claims(beacon_dir)
    if claim_id in data:
        del data[claim_id]
        _write_active_claims(data, beacon_dir=beacon_dir)
        return True
    return False


def list_local_claims(
    *,
    mine: Optional[str] = None,
    target_kind: Optional[str] = None,
    target_id: Optional[str] = None,
    beacon_dir: Optional[str] = None,
) -> list[dict]:
    """Return locally-recorded claims, optionally filtered.

    Args:
      mine: when truthy, return only claims whose from_session_id equals
        this value. Used for session restart recovery
        (`beacon claim list --mine`).
      target_kind, target_id: filter by target.
    """
    data = _read_active_claims(beacon_dir)
    out = []
    for cid, rec in data.items():
        if mine and rec.get("from_session_id") != mine:
            continue
        if target_kind or target_id:
            target = rec.get("target") or {}
            if target_kind and target.get("kind") != target_kind:
                continue
            if target_id and target.get("id") != target_id:
                continue
        out.append(rec)
    out.sort(key=lambda r: r.get("issued_at") or "")
    return out


# ---------------------------------------------------------------------------
# TODO: Cloud-mode active_claims/ subcollection wiring (= ms-55 e-1648
# follow-up). The local-mode helpers above mirror the intended layout —
# the cloud-mode equivalent should call api_client to write/read into
# the subcollection so the Web UI can render "who has what taken right
# now" without a separate API endpoint. The wire payload format is the
# same; only the persistence transport differs.
# ---------------------------------------------------------------------------
